language: python
sudo: required

dist: bionic
group: edge

cache:
    pip: true

python:
    - 3.6
    - "3.6-dev"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install automake libtool make gcc libmagic-dev -yqq
    - wget https://github.com/VirusTotal/yara/archive/v3.10.0.tar.gz
    - tar -xzvf v3.10.0.tar.gz
    - cd yara-3.10.0/ && ./bootstrap.sh && ./configure --enable-dotnet --enable-magic && make && sudo make install && cd ../
    - git clone --recursive https://github.com/VirusTotal/yara-python
    - cd yara-python 
    - python3 setup.py build --enable-magic --enable-dotnet 
    - sudo python3 setup.py install
    - pip3 install pytest codecov pytest-cov


install:
    - pip install -r requirements.txt
    - pip install -e .

script:
    - malconf
    - pytest -v --cov=malwareconfig

after_success:
    - codecov